/*
 * UCI Core Names Interface
 * Wrapper for OpenSSL core names definitions
 */

#ifndef UCI_CORE_NAMES_H
#define UCI_CORE_NAMES_H

#ifdef __cplusplus
extern "C" {
#endif

/* Include OpenSSL core names headers */
#include <openssl/core_names.h>

/* UCI parameter name aliases - map to OpenSSL equivalents */
#define UCI_PKEY_PARAM_BITS OSSL_PKEY_PARAM_BITS
#define UCI_PKEY_PARAM_MAX_SIZE OSSL_PKEY_PARAM_MAX_SIZE
#define UCI_PKEY_PARAM_SECURITY_BITS OSSL_PKEY_PARAM_SECURITY_BITS
#define UCI_PKEY_PARAM_DIGEST OSSL_PKEY_PARAM_DIGEST
#define UCI_PKEY_PARAM_CIPHER OSSL_PKEY_PARAM_CIPHER
#define UCI_PKEY_PARAM_ENGINE OSSL_PKEY_PARAM_ENGINE
#define UCI_PKEY_PARAM_PROPERTIES OSSL_PKEY_PARAM_PROPERTIES
#define UCI_PKEY_PARAM_DEFAULT_DIGEST OSSL_PKEY_PARAM_DEFAULT_DIGEST
#define UCI_PKEY_PARAM_MANDATORY_DIGEST OSSL_PKEY_PARAM_MANDATORY_DIGEST

/* Digest parameter names */
#define UCI_DIGEST_PARAM_BLOCK_SIZE OSSL_DIGEST_PARAM_BLOCK_SIZE
#define UCI_DIGEST_PARAM_SIZE OSSL_DIGEST_PARAM_SIZE
#define UCI_DIGEST_PARAM_FLAGS OSSL_DIGEST_PARAM_FLAGS

/* Cipher parameter names */
#define UCI_CIPHER_PARAM_MODE OSSL_CIPHER_PARAM_MODE
#define UCI_CIPHER_PARAM_BLOCK_SIZE OSSL_CIPHER_PARAM_BLOCK_SIZE
#define UCI_CIPHER_PARAM_KEYLEN OSSL_CIPHER_PARAM_KEYLEN
#define UCI_CIPHER_PARAM_IVLEN OSSL_CIPHER_PARAM_IVLEN
#define UCI_CIPHER_PARAM_IV OSSL_CIPHER_PARAM_IV
#define UCI_CIPHER_PARAM_AEAD_TAG OSSL_CIPHER_PARAM_AEAD_TAG
#define UCI_CIPHER_PARAM_AEAD_TAGLEN OSSL_CIPHER_PARAM_AEAD_TAGLEN

/* Algorithm parameter names */
#define UCI_ALG_PARAM_DIGEST OSSL_ALG_PARAM_DIGEST
#define UCI_ALG_PARAM_CIPHER OSSL_ALG_PARAM_CIPHER
#define UCI_ALG_PARAM_MAC OSSL_ALG_PARAM_MAC
#define UCI_ALG_PARAM_PROPERTIES OSSL_ALG_PARAM_PROPERTIES

#ifdef __cplusplus
}
#endif

#endif /* UCI_CORE_NAMES_H */
