/*
 * UCI Core Dispatch Interface
 * Wrapper for OpenSSL core dispatch functionality
 */

#ifndef UCI_CORE_DISPATCH_H
#define UCI_CORE_DISPATCH_H

#ifdef __cplusplus
extern "C" {
#endif

/* Include OpenSSL core dispatch headers */
#include <openssl/core_dispatch.h>

/* UCI function pointer type - OSSL_FUNC is defined in core_dispatch.h */
typedef void (*UCI_FUNC)(void);

/* UCI core dispatch macro */
#define UCI_CORE_MAKE_FUNC OSSL_CORE_MAKE_FUNC

/* Core function identities - map to OpenSSL equivalents */
#define UCI_FUNC_CORE_GETTABLE_PARAMS OSSL_FUNC_CORE_GETTABLE_PARAMS
#define UCI_FUNC_CORE_GET_PARAMS OSSL_FUNC_CORE_GET_PARAMS
#define UCI_FUNC_CORE_THREAD_START OSSL_FUNC_CORE_THREAD_START
#define UCI_FUNC_CORE_GET_LIBCTX OSSL_FUNC_CORE_GET_LIBCTX
#define UCI_FUNC_CORE_NEW_ERROR OSSL_FUNC_CORE_NEW_ERROR
#define UCI_FUNC_CORE_SET_ERROR_DEBUG OSSL_FUNC_CORE_SET_ERROR_DEBUG
#define UCI_FUNC_CORE_VSET_ERROR OSSL_FUNC_CORE_VSET_ERROR

/* Provider function identities */
#define UCI_FUNC_PROVIDER_TEARDOWN OSSL_FUNC_PROVIDER_TEARDOWN
#define UCI_FUNC_PROVIDER_GETTABLE_PARAMS OSSL_FUNC_PROVIDER_GETTABLE_PARAMS
#define UCI_FUNC_PROVIDER_GET_PARAMS OSSL_FUNC_PROVIDER_GET_PARAMS
#define UCI_FUNC_PROVIDER_QUERY_OPERATION OSSL_FUNC_PROVIDER_QUERY_OPERATION
#define UCI_FUNC_PROVIDER_UNQUERY_OPERATION OSSL_FUNC_PROVIDER_UNQUERY_OPERATION
#define UCI_FUNC_PROVIDER_GET_REASON_STRINGS OSSL_FUNC_PROVIDER_GET_REASON_STRINGS
#define UCI_FUNC_PROVIDER_GET_CAPABILITIES OSSL_FUNC_PROVIDER_GET_CAPABILITIES
#define UCI_FUNC_PROVIDER_SELF_TEST OSSL_FUNC_PROVIDER_SELF_TEST

/* Digest operation identities */
#define UCI_FUNC_DIGEST_NEWCTX OSSL_FUNC_DIGEST_NEWCTX
#define UCI_FUNC_DIGEST_INIT OSSL_FUNC_DIGEST_INIT
#define UCI_FUNC_DIGEST_UPDATE OSSL_FUNC_DIGEST_UPDATE
#define UCI_FUNC_DIGEST_FINAL OSSL_FUNC_DIGEST_FINAL
#define UCI_FUNC_DIGEST_FREECTX OSSL_FUNC_DIGEST_FREECTX
#define UCI_FUNC_DIGEST_DUPCTX OSSL_FUNC_DIGEST_DUPCTX

/* Cipher operation identities */
#define UCI_FUNC_CIPHER_NEWCTX OSSL_FUNC_CIPHER_NEWCTX
#define UCI_FUNC_CIPHER_ENCRYPT_INIT OSSL_FUNC_CIPHER_ENCRYPT_INIT
#define UCI_FUNC_CIPHER_DECRYPT_INIT OSSL_FUNC_CIPHER_DECRYPT_INIT
#define UCI_FUNC_CIPHER_UPDATE OSSL_FUNC_CIPHER_UPDATE
#define UCI_FUNC_CIPHER_FINAL OSSL_FUNC_CIPHER_FINAL
#define UCI_FUNC_CIPHER_FREECTX OSSL_FUNC_CIPHER_FREECTX

/* Signature operation identities */
#define UCI_FUNC_SIGNATURE_NEWCTX OSSL_FUNC_SIGNATURE_NEWCTX
#define UCI_FUNC_SIGNATURE_SIGN_INIT OSSL_FUNC_SIGNATURE_SIGN_INIT
#define UCI_FUNC_SIGNATURE_SIGN OSSL_FUNC_SIGNATURE_SIGN
#define UCI_FUNC_SIGNATURE_VERIFY_INIT OSSL_FUNC_SIGNATURE_VERIFY_INIT
#define UCI_FUNC_SIGNATURE_VERIFY OSSL_FUNC_SIGNATURE_VERIFY
#define UCI_FUNC_SIGNATURE_FREECTX OSSL_FUNC_SIGNATURE_FREECTX

/* KEM operation identities */
#define UCI_FUNC_KEM_NEWCTX OSSL_FUNC_KEM_NEWCTX
#define UCI_FUNC_KEM_ENCAPSULATE_INIT OSSL_FUNC_KEM_ENCAPSULATE_INIT
#define UCI_FUNC_KEM_ENCAPSULATE OSSL_FUNC_KEM_ENCAPSULATE
#define UCI_FUNC_KEM_DECAPSULATE_INIT OSSL_FUNC_KEM_DECAPSULATE_INIT
#define UCI_FUNC_KEM_DECAPSULATE OSSL_FUNC_KEM_DECAPSULATE
#define UCI_FUNC_KEM_FREECTX OSSL_FUNC_KEM_FREECTX

#ifdef __cplusplus
}
#endif

#endif /* UCI_CORE_DISPATCH_H */
