/* Auto-generated by gen_uci_evp_wrappers.py. Do not edit directly. */
#ifndef UCI_EVP_AUTOGEN_H
#define UCI_EVP_AUTOGEN_H

#include <openssl/evp.h>

#ifdef __cplusplus
extern "C" {
#endif

int UCI_set_default_properties(OSSL_LIB_CTX *libctx, const char *propq);
int UCI_default_properties_is_fips_enabled(OSSL_LIB_CTX *libctx);
int UCI_default_properties_enable_fips(OSSL_LIB_CTX *libctx, int enable);
OSSL_DEPRECATEDIN_3_0 EVP_MD *UCI_MD_meth_new(int md_type, int pkey_type);
OSSL_DEPRECATEDIN_3_0 EVP_MD *UCI_MD_meth_dup(const EVP_MD *md);
OSSL_DEPRECATEDIN_3_0 void UCI_MD_meth_free(EVP_MD *md);
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_input_blocksize(EVP_MD *md, int blocksize);
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_result_size(EVP_MD *md, int resultsize);
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_app_datasize(EVP_MD *md, int datasize);
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_flags(EVP_MD *md, unsigned long flags);
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_init(EVP_MD *md, int (*init)(EVP_MD_CTX *ctx));
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_update(EVP_MD *md, int (*update)(EVP_MD_CTX *ctx,
                                                     const void *data,
                                                     size_t count));
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_final(EVP_MD *md, int (*final)(EVP_MD_CTX *ctx,
                                                   unsigned char *md));
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_copy(EVP_MD *md, int (*copy)(EVP_MD_CTX *to,
                                                 const EVP_MD_CTX *from));
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_cleanup(EVP_MD *md, int (*cleanup)(EVP_MD_CTX *ctx));
OSSL_DEPRECATEDIN_3_0
int UCI_MD_meth_set_ctrl(EVP_MD *md, int (*ctrl)(EVP_MD_CTX *ctx, int cmd,
                                                 int p1, void *p2));
OSSL_DEPRECATEDIN_3_0 int UCI_MD_meth_get_input_blocksize(const EVP_MD *md);
OSSL_DEPRECATEDIN_3_0 int UCI_MD_meth_get_result_size(const EVP_MD *md);
OSSL_DEPRECATEDIN_3_0 int UCI_MD_meth_get_app_datasize(const EVP_MD *md);
OSSL_DEPRECATEDIN_3_0 unsigned long UCI_MD_meth_get_flags(const EVP_MD *md);
OSSL_DEPRECATEDIN_3_0
int (*UCI_MD_meth_get_init(const EVP_MD *md))(EVP_MD_CTX *ctx);
OSSL_DEPRECATEDIN_3_0
int (*UCI_MD_meth_get_update(const EVP_MD *md))(EVP_MD_CTX *ctx,
                                                const void *data, size_t count);
OSSL_DEPRECATEDIN_3_0
int (*UCI_MD_meth_get_final(const EVP_MD *md))(EVP_MD_CTX *ctx,
                                               unsigned char *md);
OSSL_DEPRECATEDIN_3_0
int (*UCI_MD_meth_get_copy(const EVP_MD *md))(EVP_MD_CTX *to,
                                              const EVP_MD_CTX *from);
OSSL_DEPRECATEDIN_3_0
int (*UCI_MD_meth_get_cleanup(const EVP_MD *md))(EVP_MD_CTX *ctx);
OSSL_DEPRECATEDIN_3_0
int (*UCI_MD_meth_get_ctrl(const EVP_MD *md))(EVP_MD_CTX *ctx, int cmd,
                                              int p1, void *p2);
OSSL_DEPRECATEDIN_3_0
EVP_CIPHER *UCI_CIPHER_meth_new(int cipher_type, int block_size, int key_len);
OSSL_DEPRECATEDIN_3_0
EVP_CIPHER *UCI_CIPHER_meth_dup(const EVP_CIPHER *cipher);
OSSL_DEPRECATEDIN_3_0
void UCI_CIPHER_meth_free(EVP_CIPHER *cipher);
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_iv_length(EVP_CIPHER *cipher, int iv_len);
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_flags(EVP_CIPHER *cipher, unsigned long flags);
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_impl_ctx_size(EVP_CIPHER *cipher, int ctx_size);
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_init(EVP_CIPHER *cipher, int (*init) (EVP_CIPHER_CTX *ctx,
                                          const unsigned char *key,
                                          const unsigned char *iv,
                                          int enc));
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_do_cipher(EVP_CIPHER *cipher, int (*do_cipher) (EVP_CIPHER_CTX *ctx,
                                                    unsigned char *out,
                                                    const unsigned char *in,
                                                    size_t inl));
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_cleanup(EVP_CIPHER *cipher, int (*cleanup) (EVP_CIPHER_CTX *));
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_set_asn1_params(EVP_CIPHER *cipher, int (*set_asn1_parameters) (EVP_CIPHER_CTX *,
                                                                    ASN1_TYPE *));
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_get_asn1_params(EVP_CIPHER *cipher, int (*get_asn1_parameters) (EVP_CIPHER_CTX *,
                                                                    ASN1_TYPE *));
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_meth_set_ctrl(EVP_CIPHER *cipher, int (*ctrl) (EVP_CIPHER_CTX *, int type,
                                          int arg, void *ptr));
OSSL_DEPRECATEDIN_3_0 int
(*UCI_CIPHER_meth_get_init(const EVP_CIPHER *cipher))(EVP_CIPHER_CTX *ctx,
                                                      const unsigned char *key,
                                                      const unsigned char *iv,
                                                      int enc);
OSSL_DEPRECATEDIN_3_0 int
(*UCI_CIPHER_meth_get_do_cipher(const EVP_CIPHER *cipher))(EVP_CIPHER_CTX *ctx,
                                                           unsigned char *out,
                                                           const unsigned char *in,
                                                           size_t inl);
OSSL_DEPRECATEDIN_3_0 int
(*UCI_CIPHER_meth_get_cleanup(const EVP_CIPHER *cipher))(EVP_CIPHER_CTX * param0);
OSSL_DEPRECATEDIN_3_0 int
(*UCI_CIPHER_meth_get_set_asn1_params(const EVP_CIPHER *cipher))(EVP_CIPHER_CTX *,
                                                                 ASN1_TYPE * param0);
OSSL_DEPRECATEDIN_3_0 int
(*UCI_CIPHER_meth_get_get_asn1_params(const EVP_CIPHER *cipher))(EVP_CIPHER_CTX *,
                                                                 ASN1_TYPE * param0);
OSSL_DEPRECATEDIN_3_0 int
(*UCI_CIPHER_meth_get_ctrl(const EVP_CIPHER *cipher))(EVP_CIPHER_CTX *, int type,
                                                      int arg, void *ptr);
int UCI_MD_get_type(const EVP_MD *md);
const char *UCI_MD_get0_name(const EVP_MD *md);
const char *UCI_MD_get0_description(const EVP_MD *md);
int UCI_MD_is_a(const EVP_MD *md, const char *name);
int UCI_MD_names_do_all(const EVP_MD *md, void (*fn)(const char *name, void *data), void *data);
const OSSL_PROVIDER *UCI_MD_get0_provider(const EVP_MD *md);
int UCI_MD_get_pkey_type(const EVP_MD *md);
int UCI_MD_get_size(const EVP_MD *md);
int UCI_MD_get_block_size(const EVP_MD *md);
unsigned long UCI_MD_get_flags(const EVP_MD *md);
const EVP_MD *UCI_MD_CTX_get0_md(const EVP_MD_CTX *ctx);
EVP_MD *UCI_MD_CTX_get1_md(EVP_MD_CTX *ctx);
OSSL_DEPRECATEDIN_3_0
const EVP_MD *UCI_MD_CTX_md(const EVP_MD_CTX *ctx);
OSSL_DEPRECATEDIN_3_0
int (*UCI_MD_CTX_update_fn(EVP_MD_CTX *ctx))(EVP_MD_CTX *ctx,
                                             const void *data, size_t count);
OSSL_DEPRECATEDIN_3_0
void UCI_MD_CTX_set_update_fn(EVP_MD_CTX *ctx, int (*update) (EVP_MD_CTX *ctx,
                                             const void *data, size_t count));
EVP_PKEY_CTX *UCI_MD_CTX_get_pkey_ctx(const EVP_MD_CTX *ctx);
void UCI_MD_CTX_set_pkey_ctx(EVP_MD_CTX *ctx, EVP_PKEY_CTX *pctx);
void *UCI_MD_CTX_get0_md_data(const EVP_MD_CTX *ctx);
int UCI_CIPHER_get_nid(const EVP_CIPHER *cipher);
const char *UCI_CIPHER_get0_name(const EVP_CIPHER *cipher);
const char *UCI_CIPHER_get0_description(const EVP_CIPHER *cipher);
int UCI_CIPHER_is_a(const EVP_CIPHER *cipher, const char *name);
int UCI_CIPHER_names_do_all(const EVP_CIPHER *cipher, void (*fn)(const char *name, void *data), void *data);
const OSSL_PROVIDER *UCI_CIPHER_get0_provider(const EVP_CIPHER *cipher);
int UCI_CIPHER_get_block_size(const EVP_CIPHER *cipher);
OSSL_DEPRECATEDIN_3_0
int UCI_CIPHER_impl_ctx_size(const EVP_CIPHER *cipher);
int UCI_CIPHER_get_key_length(const EVP_CIPHER *cipher);
int UCI_CIPHER_get_iv_length(const EVP_CIPHER *cipher);
unsigned long UCI_CIPHER_get_flags(const EVP_CIPHER *cipher);
int UCI_CIPHER_get_mode(const EVP_CIPHER *cipher);
int UCI_CIPHER_get_type(const EVP_CIPHER *cipher);
EVP_CIPHER *UCI_CIPHER_fetch(OSSL_LIB_CTX *ctx, const char *algorithm, const char *properties);
int UCI_CIPHER_up_ref(EVP_CIPHER *cipher);
void UCI_CIPHER_free(EVP_CIPHER *cipher);
const EVP_CIPHER *UCI_CIPHER_CTX_get0_cipher(const EVP_CIPHER_CTX *ctx);
EVP_CIPHER *UCI_CIPHER_CTX_get1_cipher(EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_is_encrypting(const EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_get_nid(const EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_get_block_size(const EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_get_key_length(const EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_get_iv_length(const EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_get_tag_length(const EVP_CIPHER_CTX *ctx);
const EVP_CIPHER *UCI_CIPHER_CTX_cipher(const EVP_CIPHER_CTX *ctx);
OSSL_DEPRECATEDIN_3_0 const unsigned char *UCI_CIPHER_CTX_iv(const EVP_CIPHER_CTX *ctx);
OSSL_DEPRECATEDIN_3_0 const unsigned char *UCI_CIPHER_CTX_original_iv(const EVP_CIPHER_CTX *ctx);
OSSL_DEPRECATEDIN_3_0 unsigned char *UCI_CIPHER_CTX_iv_noconst(EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_get_updated_iv(EVP_CIPHER_CTX *ctx, void *buf, size_t len);
int UCI_CIPHER_CTX_get_original_iv(EVP_CIPHER_CTX *ctx, void *buf, size_t len);
OSSL_DEPRECATEDIN_3_0
unsigned char *UCI_CIPHER_CTX_buf_noconst(EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_get_num(const EVP_CIPHER_CTX *ctx);
int UCI_CIPHER_CTX_set_num(EVP_CIPHER_CTX *ctx, int num);
int UCI_CIPHER_CTX_copy(EVP_CIPHER_CTX *out, const EVP_CIPHER_CTX *in);
void *UCI_CIPHER_CTX_get_app_data(const EVP_CIPHER_CTX *ctx);
void UCI_CIPHER_CTX_set_app_data(EVP_CIPHER_CTX *ctx, void *data);
void *UCI_CIPHER_CTX_get_cipher_data(const EVP_CIPHER_CTX *ctx);
void *UCI_CIPHER_CTX_set_cipher_data(EVP_CIPHER_CTX *ctx, void *cipher_data);
int UCI_Cipher(EVP_CIPHER_CTX *c, unsigned char *out, const unsigned char *in, unsigned int inl);
int UCI_MD_get_params(const EVP_MD *digest, OSSL_PARAM params[]);
int UCI_MD_CTX_set_params(EVP_MD_CTX *ctx, const OSSL_PARAM params[]);
int UCI_MD_CTX_get_params(EVP_MD_CTX *ctx, OSSL_PARAM params[]);
const OSSL_PARAM *UCI_MD_gettable_params(const EVP_MD *digest);
const OSSL_PARAM *UCI_MD_settable_ctx_params(const EVP_MD *md);
const OSSL_PARAM *UCI_MD_gettable_ctx_params(const EVP_MD *md);
const OSSL_PARAM *UCI_MD_CTX_settable_params(EVP_MD_CTX *ctx);
const OSSL_PARAM *UCI_MD_CTX_gettable_params(EVP_MD_CTX *ctx);
int UCI_MD_CTX_ctrl(EVP_MD_CTX *ctx, int cmd, int p1, void *p2);
EVP_MD_CTX *UCI_MD_CTX_new(void);
int UCI_MD_CTX_reset(EVP_MD_CTX *ctx);
void UCI_MD_CTX_free(EVP_MD_CTX *ctx);
__owur int UCI_MD_CTX_copy_ex(EVP_MD_CTX *out, const EVP_MD_CTX *in);
void UCI_MD_CTX_set_flags(EVP_MD_CTX *ctx, int flags);
void UCI_MD_CTX_clear_flags(EVP_MD_CTX *ctx, int flags);
int UCI_MD_CTX_test_flags(const EVP_MD_CTX *ctx, int flags);
__owur int UCI_DigestInit_ex2(EVP_MD_CTX *ctx, const EVP_MD *type, const OSSL_PARAM params[]);
__owur int UCI_DigestInit_ex(EVP_MD_CTX *ctx, const EVP_MD *type, ENGINE *impl);
__owur int UCI_DigestUpdate(EVP_MD_CTX *ctx, const void *d, size_t cnt);
__owur int UCI_DigestFinal_ex(EVP_MD_CTX *ctx, unsigned char *md, unsigned int *s);
__owur int UCI_Digest(const void *data, size_t count, unsigned char *md, unsigned int *size, const EVP_MD *type, ENGINE *impl);
__owur int UCI_Q_digest(OSSL_LIB_CTX *libctx, const char *name, const char *propq, const void *data, size_t datalen, unsigned char *md, size_t *mdlen);
__owur int UCI_MD_CTX_copy(EVP_MD_CTX *out, const EVP_MD_CTX *in);
__owur int UCI_DigestInit(EVP_MD_CTX *ctx, const EVP_MD *type);
__owur int UCI_DigestFinal(EVP_MD_CTX *ctx, unsigned char *md, unsigned int *s);
__owur int UCI_DigestFinalXOF(EVP_MD_CTX *ctx, unsigned char *md, size_t len);
__owur EVP_MD *UCI_MD_fetch(OSSL_LIB_CTX *ctx, const char *algorithm, const char *properties);
int UCI_MD_up_ref(EVP_MD *md);
void UCI_MD_free(EVP_MD *md);
int UCI_read_pw_string(char *buf, int length, const char *prompt, int verify);
int UCI_read_pw_string_min(char *buf, int minlen, int maxlen, const char *prompt, int verify);
void UCI_set_pw_prompt(const char *prompt);
char *UCI_get_pw_prompt(void);
__owur int UCI_BytesToKey(const EVP_CIPHER *type, const EVP_MD *md, const unsigned char *salt, const unsigned char *data, int datal, int count, unsigned char *key, unsigned char *iv);
void UCI_CIPHER_CTX_set_flags(EVP_CIPHER_CTX *ctx, int flags);
void UCI_CIPHER_CTX_clear_flags(EVP_CIPHER_CTX *ctx, int flags);
int UCI_CIPHER_CTX_test_flags(const EVP_CIPHER_CTX *ctx, int flags);
__owur int UCI_EncryptInit(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv);
int UCI_EncryptInit_ex(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv);
__owur int UCI_EncryptInit_ex2(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv, const OSSL_PARAM params[]);
int UCI_EncryptUpdate(EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl);
int UCI_EncryptFinal_ex(EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl);
int UCI_EncryptFinal(EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl);
__owur int UCI_DecryptInit(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv);
int UCI_DecryptInit_ex(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv);
__owur int UCI_DecryptInit_ex2(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv, const OSSL_PARAM params[]);
int UCI_DecryptUpdate(EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl);
__owur int UCI_DecryptFinal(EVP_CIPHER_CTX *ctx, unsigned char *outm, int *outl);
int UCI_DecryptFinal_ex(EVP_CIPHER_CTX *ctx, unsigned char *outm, int *outl);
__owur int UCI_CipherInit(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv, int enc);
int UCI_CipherInit_ex(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv, int enc);
__owur int UCI_CipherInit_ex2(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv, int enc, const OSSL_PARAM params[]);
__owur int UCI_CipherUpdate(EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl);
__owur int UCI_CipherFinal(EVP_CIPHER_CTX *ctx, unsigned char *outm, int *outl);
__owur int UCI_CipherFinal_ex(EVP_CIPHER_CTX *ctx, unsigned char *outm, int *outl);
__owur int UCI_SignFinal(EVP_MD_CTX *ctx, unsigned char *md, unsigned int *s, EVP_PKEY *pkey);
__owur int UCI_SignFinal_ex(EVP_MD_CTX *ctx, unsigned char *md, unsigned int *s, EVP_PKEY *pkey, OSSL_LIB_CTX *libctx, const char *propq);
__owur int UCI_DigestSign(EVP_MD_CTX *ctx, unsigned char *sigret, size_t *siglen, const unsigned char *tbs, size_t tbslen);
__owur int UCI_VerifyFinal(EVP_MD_CTX *ctx, const unsigned char *sigbuf, unsigned int siglen, EVP_PKEY *pkey);
__owur int UCI_VerifyFinal_ex(EVP_MD_CTX *ctx, const unsigned char *sigbuf, unsigned int siglen, EVP_PKEY *pkey, OSSL_LIB_CTX *libctx, const char *propq);
__owur int UCI_DigestVerify(EVP_MD_CTX *ctx, const unsigned char *sigret, size_t siglen, const unsigned char *tbs, size_t tbslen);
int UCI_DigestSignInit_ex(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx, const char *mdname, OSSL_LIB_CTX *libctx, const char *props, EVP_PKEY *pkey, const OSSL_PARAM params[]);
int UCI_DigestSignInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx, const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey);
int UCI_DigestSignUpdate(EVP_MD_CTX *ctx, const void *data, size_t dsize);
__owur int UCI_DigestSignFinal(EVP_MD_CTX *ctx, unsigned char *sigret, size_t *siglen);
int UCI_DigestVerifyInit_ex(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx, const char *mdname, OSSL_LIB_CTX *libctx, const char *props, EVP_PKEY *pkey, const OSSL_PARAM params[]);
__owur int UCI_DigestVerifyInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx, const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey);
int UCI_DigestVerifyUpdate(EVP_MD_CTX *ctx, const void *data, size_t dsize);
__owur int UCI_DigestVerifyFinal(EVP_MD_CTX *ctx, const unsigned char *sig, size_t siglen);
__owur int UCI_OpenInit(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *type, const unsigned char *ek, int ekl, const unsigned char *iv, EVP_PKEY *priv);
__owur int UCI_OpenFinal(EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl);
__owur int UCI_SealInit(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *type, unsigned char **ek, int *ekl, unsigned char *iv, EVP_PKEY **pubk, int npubk);
__owur int UCI_SealFinal(EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl);
EVP_ENCODE_CTX *UCI_ENCODE_CTX_new(void);
void UCI_ENCODE_CTX_free(EVP_ENCODE_CTX *ctx);
int UCI_ENCODE_CTX_copy(EVP_ENCODE_CTX *dctx, const EVP_ENCODE_CTX *sctx);
int UCI_ENCODE_CTX_num(EVP_ENCODE_CTX *ctx);
void UCI_EncodeInit(EVP_ENCODE_CTX *ctx);
int UCI_EncodeUpdate(EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl);
void UCI_EncodeFinal(EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl);
int UCI_EncodeBlock(unsigned char *t, const unsigned char *f, int n);
void UCI_DecodeInit(EVP_ENCODE_CTX *ctx);
int UCI_DecodeUpdate(EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl);
int UCI_DecodeFinal(EVP_ENCODE_CTX *ctx, unsigned
                    char *out, int *outl);
int UCI_DecodeBlock(unsigned char *t, const unsigned char *f, int n);
EVP_CIPHER_CTX *UCI_CIPHER_CTX_new(void);
int UCI_CIPHER_CTX_reset(EVP_CIPHER_CTX *c);
void UCI_CIPHER_CTX_free(EVP_CIPHER_CTX *c);
int UCI_CIPHER_CTX_set_key_length(EVP_CIPHER_CTX *x, int keylen);
int UCI_CIPHER_CTX_set_padding(EVP_CIPHER_CTX *c, int pad);
int UCI_CIPHER_CTX_ctrl(EVP_CIPHER_CTX *ctx, int type, int arg, void *ptr);
int UCI_CIPHER_CTX_rand_key(EVP_CIPHER_CTX *ctx, unsigned char *key);
int UCI_CIPHER_get_params(EVP_CIPHER *cipher, OSSL_PARAM params[]);
int UCI_CIPHER_CTX_set_params(EVP_CIPHER_CTX *ctx, const OSSL_PARAM params[]);
int UCI_CIPHER_CTX_get_params(EVP_CIPHER_CTX *ctx, OSSL_PARAM params[]);
const OSSL_PARAM *UCI_CIPHER_gettable_params(const EVP_CIPHER *cipher);
const OSSL_PARAM *UCI_CIPHER_settable_ctx_params(const EVP_CIPHER *cipher);
const OSSL_PARAM *UCI_CIPHER_gettable_ctx_params(const EVP_CIPHER *cipher);
const OSSL_PARAM *UCI_CIPHER_CTX_settable_params(EVP_CIPHER_CTX *ctx);
const OSSL_PARAM *UCI_CIPHER_CTX_gettable_params(EVP_CIPHER_CTX *ctx);
const EVP_MD *UCI_md_null(void);
#ifndef OPENSSL_NO_MD2
const EVP_MD *UCI_md2(void);
#endif
const EVP_MD *UCI_md4(void);
const EVP_MD *UCI_md5(void);
const EVP_MD *UCI_md5_sha1(void);
const EVP_MD *UCI_blake2b512(void);
const EVP_MD *UCI_blake2s256(void);
const EVP_MD *UCI_sha1(void);
const EVP_MD *UCI_sha224(void);
const EVP_MD *UCI_sha256(void);
const EVP_MD *UCI_sha384(void);
const EVP_MD *UCI_sha512(void);
const EVP_MD *UCI_sha512_224(void);
const EVP_MD *UCI_sha512_256(void);
const EVP_MD *UCI_sha3_224(void);
const EVP_MD *UCI_sha3_256(void);
const EVP_MD *UCI_sha3_384(void);
const EVP_MD *UCI_sha3_512(void);
const EVP_MD *UCI_shake128(void);
const EVP_MD *UCI_shake256(void);
#ifndef OPENSSL_NO_MDC2
const EVP_MD *UCI_mdc2(void);
#endif
const EVP_MD *UCI_ripemd160(void);
const EVP_MD *UCI_whirlpool(void);
const EVP_MD *UCI_sm3(void);
const EVP_CIPHER *UCI_enc_null(void);
const EVP_CIPHER *UCI_des_ecb(void);
const EVP_CIPHER *UCI_des_ede(void);
const EVP_CIPHER *UCI_des_ede3(void);
const EVP_CIPHER *UCI_des_ede_ecb(void);
const EVP_CIPHER *UCI_des_ede3_ecb(void);
const EVP_CIPHER *UCI_des_cfb64(void);
const EVP_CIPHER *UCI_des_cfb1(void);
const EVP_CIPHER *UCI_des_cfb8(void);
const EVP_CIPHER *UCI_des_ede_cfb64(void);
const EVP_CIPHER *UCI_des_ede3_cfb64(void);
const EVP_CIPHER *UCI_des_ede3_cfb1(void);
const EVP_CIPHER *UCI_des_ede3_cfb8(void);
const EVP_CIPHER *UCI_des_ofb(void);
const EVP_CIPHER *UCI_des_ede_ofb(void);
const EVP_CIPHER *UCI_des_ede3_ofb(void);
const EVP_CIPHER *UCI_des_cbc(void);
const EVP_CIPHER *UCI_des_ede_cbc(void);
const EVP_CIPHER *UCI_des_ede3_cbc(void);
const EVP_CIPHER *UCI_desx_cbc(void);
const EVP_CIPHER *UCI_des_ede3_wrap(void);
const EVP_CIPHER *UCI_rc4(void);
const EVP_CIPHER *UCI_rc4_40(void);
const EVP_CIPHER *UCI_rc4_hmac_md5(void);
#ifndef OPENSSL_NO_IDEA
const EVP_CIPHER *UCI_idea_ecb(void);
const EVP_CIPHER *UCI_idea_cfb64(void);
const EVP_CIPHER *UCI_idea_ofb(void);
const EVP_CIPHER *UCI_idea_cbc(void);
#endif
const EVP_CIPHER *UCI_rc2_ecb(void);
const EVP_CIPHER *UCI_rc2_cbc(void);
const EVP_CIPHER *UCI_rc2_40_cbc(void);
const EVP_CIPHER *UCI_rc2_64_cbc(void);
const EVP_CIPHER *UCI_rc2_cfb64(void);
const EVP_CIPHER *UCI_rc2_ofb(void);
const EVP_CIPHER *UCI_bf_ecb(void);
const EVP_CIPHER *UCI_bf_cbc(void);
const EVP_CIPHER *UCI_bf_cfb64(void);
const EVP_CIPHER *UCI_bf_ofb(void);
const EVP_CIPHER *UCI_cast5_ecb(void);
const EVP_CIPHER *UCI_cast5_cbc(void);
const EVP_CIPHER *UCI_cast5_cfb64(void);
const EVP_CIPHER *UCI_cast5_ofb(void);
#ifndef OPENSSL_NO_RC5
const EVP_CIPHER *UCI_rc5_32_12_16_cbc(void);
const EVP_CIPHER *UCI_rc5_32_12_16_ecb(void);
const EVP_CIPHER *UCI_rc5_32_12_16_cfb64(void);
const EVP_CIPHER *UCI_rc5_32_12_16_ofb(void);
#endif
const EVP_CIPHER *UCI_aes_128_ecb(void);
const EVP_CIPHER *UCI_aes_128_cbc(void);
const EVP_CIPHER *UCI_aes_128_cfb1(void);
const EVP_CIPHER *UCI_aes_128_cfb8(void);
const EVP_CIPHER *UCI_aes_128_cfb128(void);
const EVP_CIPHER *UCI_aes_128_ofb(void);
const EVP_CIPHER *UCI_aes_128_ctr(void);
const EVP_CIPHER *UCI_aes_128_ccm(void);
const EVP_CIPHER *UCI_aes_128_gcm(void);
const EVP_CIPHER *UCI_aes_128_xts(void);
const EVP_CIPHER *UCI_aes_128_wrap(void);
const EVP_CIPHER *UCI_aes_128_wrap_pad(void);
const EVP_CIPHER *UCI_aes_128_ocb(void);
const EVP_CIPHER *UCI_aes_192_ecb(void);
const EVP_CIPHER *UCI_aes_192_cbc(void);
const EVP_CIPHER *UCI_aes_192_cfb1(void);
const EVP_CIPHER *UCI_aes_192_cfb8(void);
const EVP_CIPHER *UCI_aes_192_cfb128(void);
const EVP_CIPHER *UCI_aes_192_ofb(void);
const EVP_CIPHER *UCI_aes_192_ctr(void);
const EVP_CIPHER *UCI_aes_192_ccm(void);
const EVP_CIPHER *UCI_aes_192_gcm(void);
const EVP_CIPHER *UCI_aes_192_wrap(void);
const EVP_CIPHER *UCI_aes_192_wrap_pad(void);
const EVP_CIPHER *UCI_aes_192_ocb(void);
const EVP_CIPHER *UCI_aes_256_ecb(void);
const EVP_CIPHER *UCI_aes_256_cbc(void);
const EVP_CIPHER *UCI_aes_256_cfb1(void);
const EVP_CIPHER *UCI_aes_256_cfb8(void);
const EVP_CIPHER *UCI_aes_256_cfb128(void);
const EVP_CIPHER *UCI_aes_256_ofb(void);
const EVP_CIPHER *UCI_aes_256_ctr(void);
const EVP_CIPHER *UCI_aes_256_ccm(void);
const EVP_CIPHER *UCI_aes_256_gcm(void);
const EVP_CIPHER *UCI_aes_256_xts(void);
const EVP_CIPHER *UCI_aes_256_wrap(void);
const EVP_CIPHER *UCI_aes_256_wrap_pad(void);
const EVP_CIPHER *UCI_aes_256_ocb(void);
const EVP_CIPHER *UCI_aes_128_cbc_hmac_sha1(void);
const EVP_CIPHER *UCI_aes_256_cbc_hmac_sha1(void);
const EVP_CIPHER *UCI_aes_128_cbc_hmac_sha256(void);
const EVP_CIPHER *UCI_aes_256_cbc_hmac_sha256(void);
const EVP_CIPHER *UCI_aria_128_ecb(void);
const EVP_CIPHER *UCI_aria_128_cbc(void);
const EVP_CIPHER *UCI_aria_128_cfb1(void);
const EVP_CIPHER *UCI_aria_128_cfb8(void);
const EVP_CIPHER *UCI_aria_128_cfb128(void);
const EVP_CIPHER *UCI_aria_128_ctr(void);
const EVP_CIPHER *UCI_aria_128_ofb(void);
const EVP_CIPHER *UCI_aria_128_gcm(void);
const EVP_CIPHER *UCI_aria_128_ccm(void);
const EVP_CIPHER *UCI_aria_192_ecb(void);
const EVP_CIPHER *UCI_aria_192_cbc(void);
const EVP_CIPHER *UCI_aria_192_cfb1(void);
const EVP_CIPHER *UCI_aria_192_cfb8(void);
const EVP_CIPHER *UCI_aria_192_cfb128(void);
const EVP_CIPHER *UCI_aria_192_ctr(void);
const EVP_CIPHER *UCI_aria_192_ofb(void);
const EVP_CIPHER *UCI_aria_192_gcm(void);
const EVP_CIPHER *UCI_aria_192_ccm(void);
const EVP_CIPHER *UCI_aria_256_ecb(void);
const EVP_CIPHER *UCI_aria_256_cbc(void);
const EVP_CIPHER *UCI_aria_256_cfb1(void);
const EVP_CIPHER *UCI_aria_256_cfb8(void);
const EVP_CIPHER *UCI_aria_256_cfb128(void);
const EVP_CIPHER *UCI_aria_256_ctr(void);
const EVP_CIPHER *UCI_aria_256_ofb(void);
const EVP_CIPHER *UCI_aria_256_gcm(void);
const EVP_CIPHER *UCI_aria_256_ccm(void);
const EVP_CIPHER *UCI_camellia_128_ecb(void);
const EVP_CIPHER *UCI_camellia_128_cbc(void);
const EVP_CIPHER *UCI_camellia_128_cfb1(void);
const EVP_CIPHER *UCI_camellia_128_cfb8(void);
const EVP_CIPHER *UCI_camellia_128_cfb128(void);
const EVP_CIPHER *UCI_camellia_128_ofb(void);
const EVP_CIPHER *UCI_camellia_128_ctr(void);
const EVP_CIPHER *UCI_camellia_192_ecb(void);
const EVP_CIPHER *UCI_camellia_192_cbc(void);
const EVP_CIPHER *UCI_camellia_192_cfb1(void);
const EVP_CIPHER *UCI_camellia_192_cfb8(void);
const EVP_CIPHER *UCI_camellia_192_cfb128(void);
const EVP_CIPHER *UCI_camellia_192_ofb(void);
const EVP_CIPHER *UCI_camellia_192_ctr(void);
const EVP_CIPHER *UCI_camellia_256_ecb(void);
const EVP_CIPHER *UCI_camellia_256_cbc(void);
const EVP_CIPHER *UCI_camellia_256_cfb1(void);
const EVP_CIPHER *UCI_camellia_256_cfb8(void);
const EVP_CIPHER *UCI_camellia_256_cfb128(void);
const EVP_CIPHER *UCI_camellia_256_ofb(void);
const EVP_CIPHER *UCI_camellia_256_ctr(void);
const EVP_CIPHER *UCI_chacha20(void);
const EVP_CIPHER *UCI_chacha20_poly1305(void);
const EVP_CIPHER *UCI_seed_ecb(void);
const EVP_CIPHER *UCI_seed_cbc(void);
const EVP_CIPHER *UCI_seed_cfb128(void);
const EVP_CIPHER *UCI_seed_ofb(void);
const EVP_CIPHER *UCI_sm4_ecb(void);
const EVP_CIPHER *UCI_sm4_cbc(void);
const EVP_CIPHER *UCI_sm4_cfb128(void);
const EVP_CIPHER *UCI_sm4_ofb(void);
const EVP_CIPHER *UCI_sm4_ctr(void);
int UCI_add_cipher(const EVP_CIPHER *cipher);
int UCI_add_digest(const EVP_MD *digest);
const EVP_CIPHER *UCI_get_cipherbyname(const char *name);
const EVP_MD *UCI_get_digestbyname(const char *name);
void UCI_CIPHER_do_all(void (*fn) (const EVP_CIPHER *ciph,
                                   const char *from, const char *to, void *x), void *arg);
void UCI_CIPHER_do_all_sorted(void (*fn)
                               (const EVP_CIPHER *ciph, const char *from,
                                const char *to, void *x), void *arg);
void UCI_CIPHER_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_CIPHER *cipher, void *arg), void *arg);
void UCI_MD_do_all(void (*fn) (const EVP_MD *ciph,
                               const char *from, const char *to, void *x), void *arg);
void UCI_MD_do_all_sorted(void (*fn)
                           (const EVP_MD *ciph, const char *from,
                            const char *to, void *x), void *arg);
void UCI_MD_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_MD *md, void *arg), void *arg);
EVP_MAC *UCI_MAC_fetch(OSSL_LIB_CTX *libctx, const char *algorithm, const char *properties);
int UCI_MAC_up_ref(EVP_MAC *mac);
void UCI_MAC_free(EVP_MAC *mac);
const char *UCI_MAC_get0_name(const EVP_MAC *mac);
const char *UCI_MAC_get0_description(const EVP_MAC *mac);
int UCI_MAC_is_a(const EVP_MAC *mac, const char *name);
const OSSL_PROVIDER *UCI_MAC_get0_provider(const EVP_MAC *mac);
int UCI_MAC_get_params(EVP_MAC *mac, OSSL_PARAM params[]);
EVP_MAC_CTX *UCI_MAC_CTX_new(EVP_MAC *mac);
void UCI_MAC_CTX_free(EVP_MAC_CTX *ctx);
EVP_MAC_CTX *UCI_MAC_CTX_dup(const EVP_MAC_CTX *src);
EVP_MAC *UCI_MAC_CTX_get0_mac(EVP_MAC_CTX *ctx);
int UCI_MAC_CTX_get_params(EVP_MAC_CTX *ctx, OSSL_PARAM params[]);
int UCI_MAC_CTX_set_params(EVP_MAC_CTX *ctx, const OSSL_PARAM params[]);
size_t UCI_MAC_CTX_get_mac_size(EVP_MAC_CTX *ctx);
size_t UCI_MAC_CTX_get_block_size(EVP_MAC_CTX *ctx);
unsigned char *UCI_Q_mac(OSSL_LIB_CTX *libctx, const char *name, const char *propq, const char *subalg, const OSSL_PARAM *params, const void *key, size_t keylen, const unsigned char *data, size_t datalen, unsigned char *out, size_t outsize, size_t *outlen);
int UCI_MAC_init(EVP_MAC_CTX *ctx, const unsigned char *key, size_t keylen, const OSSL_PARAM params[]);
int UCI_MAC_update(EVP_MAC_CTX *ctx, const unsigned char *data, size_t datalen);
int UCI_MAC_final(EVP_MAC_CTX *ctx, unsigned char *out, size_t *outl, size_t outsize);
int UCI_MAC_finalXOF(EVP_MAC_CTX *ctx, unsigned char *out, size_t outsize);
const OSSL_PARAM *UCI_MAC_gettable_params(const EVP_MAC *mac);
const OSSL_PARAM *UCI_MAC_gettable_ctx_params(const EVP_MAC *mac);
const OSSL_PARAM *UCI_MAC_settable_ctx_params(const EVP_MAC *mac);
const OSSL_PARAM *UCI_MAC_CTX_gettable_params(EVP_MAC_CTX *ctx);
const OSSL_PARAM *UCI_MAC_CTX_settable_params(EVP_MAC_CTX *ctx);
void UCI_MAC_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_MAC *mac, void *arg), void *arg);
int UCI_MAC_names_do_all(const EVP_MAC *mac, void (*fn)(const char *name, void *data), void *data);
EVP_RAND *UCI_RAND_fetch(OSSL_LIB_CTX *libctx, const char *algorithm, const char *properties);
int UCI_RAND_up_ref(EVP_RAND *rand);
void UCI_RAND_free(EVP_RAND *rand);
const char *UCI_RAND_get0_name(const EVP_RAND *rand);
const char *UCI_RAND_get0_description(const EVP_RAND *md);
int UCI_RAND_is_a(const EVP_RAND *rand, const char *name);
const OSSL_PROVIDER *UCI_RAND_get0_provider(const EVP_RAND *rand);
int UCI_RAND_get_params(EVP_RAND *rand, OSSL_PARAM params[]);
EVP_RAND_CTX *UCI_RAND_CTX_new(EVP_RAND *rand, EVP_RAND_CTX *parent);
void UCI_RAND_CTX_free(EVP_RAND_CTX *ctx);
EVP_RAND *UCI_RAND_CTX_get0_rand(EVP_RAND_CTX *ctx);
int UCI_RAND_CTX_get_params(EVP_RAND_CTX *ctx, OSSL_PARAM params[]);
int UCI_RAND_CTX_set_params(EVP_RAND_CTX *ctx, const OSSL_PARAM params[]);
const OSSL_PARAM *UCI_RAND_gettable_params(const EVP_RAND *rand);
const OSSL_PARAM *UCI_RAND_gettable_ctx_params(const EVP_RAND *rand);
const OSSL_PARAM *UCI_RAND_settable_ctx_params(const EVP_RAND *rand);
const OSSL_PARAM *UCI_RAND_CTX_gettable_params(EVP_RAND_CTX *ctx);
const OSSL_PARAM *UCI_RAND_CTX_settable_params(EVP_RAND_CTX *ctx);
void UCI_RAND_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_RAND *rand, void *arg), void *arg);
int UCI_RAND_names_do_all(const EVP_RAND *rand, void (*fn)(const char *name, void *data), void *data);
__owur int UCI_RAND_instantiate(EVP_RAND_CTX *ctx, unsigned int strength, int prediction_resistance, const unsigned char *pstr, size_t pstr_len, const OSSL_PARAM params[]);
int UCI_RAND_uninstantiate(EVP_RAND_CTX *ctx);
__owur int UCI_RAND_generate(EVP_RAND_CTX *ctx, unsigned char *out, size_t outlen, unsigned int strength, int prediction_resistance, const unsigned char *addin, size_t addin_len);
int UCI_RAND_reseed(EVP_RAND_CTX *ctx, int prediction_resistance, const unsigned char *ent, size_t ent_len, const unsigned char *addin, size_t addin_len);
__owur int UCI_RAND_nonce(EVP_RAND_CTX *ctx, unsigned char *out, size_t outlen);
__owur int UCI_RAND_enable_locking(EVP_RAND_CTX *ctx);
int UCI_RAND_verify_zeroization(EVP_RAND_CTX *ctx);
unsigned int UCI_RAND_get_strength(EVP_RAND_CTX *ctx);
int UCI_RAND_get_state(EVP_RAND_CTX *ctx);
OSSL_DEPRECATEDIN_3_0 int UCI_PKEY_decrypt_old(unsigned char *dec_key, const unsigned char *enc_key, int enc_key_len, EVP_PKEY *private_key);
OSSL_DEPRECATEDIN_3_0 int UCI_PKEY_encrypt_old(unsigned char *enc_key, const unsigned char *key, int key_len, EVP_PKEY *pub_key);
int UCI_PKEY_is_a(const EVP_PKEY *pkey, const char *name);
int UCI_PKEY_type_names_do_all(const EVP_PKEY *pkey, void (*fn)(const char *name, void *data), void *data);
int UCI_PKEY_type(int type);
int UCI_PKEY_get_id(const EVP_PKEY *pkey);
int UCI_PKEY_get_base_id(const EVP_PKEY *pkey);
int UCI_PKEY_get_bits(const EVP_PKEY *pkey);
int UCI_PKEY_get_security_bits(const EVP_PKEY *pkey);
int UCI_PKEY_get_size(const EVP_PKEY *pkey);
int UCI_PKEY_can_sign(const EVP_PKEY *pkey);
int UCI_PKEY_set_type(EVP_PKEY *pkey, int type);
int UCI_PKEY_set_type_str(EVP_PKEY *pkey, const char *str, int len);
int UCI_PKEY_set_type_by_keymgmt(EVP_PKEY *pkey, EVP_KEYMGMT *keymgmt);
OSSL_DEPRECATEDIN_3_0
int UCI_PKEY_set1_engine(EVP_PKEY *pkey, ENGINE *e);
OSSL_DEPRECATEDIN_3_0
ENGINE *UCI_PKEY_get0_engine(const EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0
int UCI_PKEY_assign(EVP_PKEY *pkey, int type, void *key);
OSSL_DEPRECATEDIN_3_0
void *UCI_PKEY_get0(const EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0
const unsigned char *UCI_PKEY_get0_hmac(const EVP_PKEY *pkey, size_t *len);
OSSL_DEPRECATEDIN_3_0
const unsigned char *UCI_PKEY_get0_poly1305(const EVP_PKEY *pkey, size_t *len);
OSSL_DEPRECATEDIN_3_0
const unsigned char *UCI_PKEY_get0_siphash(const EVP_PKEY *pkey, size_t *len);
OSSL_DEPRECATEDIN_3_0
int UCI_PKEY_set1_RSA(EVP_PKEY *pkey, struct rsa_st *key);
OSSL_DEPRECATEDIN_3_0
const struct rsa_st *UCI_PKEY_get0_RSA(const EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0
struct rsa_st *UCI_PKEY_get1_RSA(EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0
int UCI_PKEY_set1_DSA(EVP_PKEY *pkey, struct dsa_st *key);
OSSL_DEPRECATEDIN_3_0
const struct dsa_st *UCI_PKEY_get0_DSA(const EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0
struct dsa_st *UCI_PKEY_get1_DSA(EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0 int UCI_PKEY_set1_DH(EVP_PKEY *pkey, struct dh_st *key);
OSSL_DEPRECATEDIN_3_0 const struct dh_st *UCI_PKEY_get0_DH(const EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0 struct dh_st *UCI_PKEY_get1_DH(EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0
int UCI_PKEY_set1_EC_KEY(EVP_PKEY *pkey, struct ec_key_st *key);
OSSL_DEPRECATEDIN_3_0
const struct ec_key_st *UCI_PKEY_get0_EC_KEY(const EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0
struct ec_key_st *UCI_PKEY_get1_EC_KEY(EVP_PKEY *pkey);
EVP_PKEY *UCI_PKEY_new(void);
int UCI_PKEY_up_ref(EVP_PKEY *pkey);
EVP_PKEY *UCI_PKEY_dup(EVP_PKEY *pkey);
void UCI_PKEY_free(EVP_PKEY *pkey);
const char *UCI_PKEY_get0_description(const EVP_PKEY *pkey);
const OSSL_PROVIDER *UCI_PKEY_get0_provider(const EVP_PKEY *key);
int UCI_PKEY_copy_parameters(EVP_PKEY *to, const EVP_PKEY *from);
int UCI_PKEY_missing_parameters(const EVP_PKEY *pkey);
int UCI_PKEY_save_parameters(EVP_PKEY *pkey, int mode);
int UCI_PKEY_parameters_eq(const EVP_PKEY *a, const EVP_PKEY *b);
int UCI_PKEY_eq(const EVP_PKEY *a, const EVP_PKEY *b);
OSSL_DEPRECATEDIN_3_0
int UCI_PKEY_cmp_parameters(const EVP_PKEY *a, const EVP_PKEY *b);
OSSL_DEPRECATEDIN_3_0
int UCI_PKEY_cmp(const EVP_PKEY *a, const EVP_PKEY *b);
int UCI_PKEY_print_public(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx);
int UCI_PKEY_print_private(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx);
int UCI_PKEY_print_params(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx);
int UCI_PKEY_print_public_fp(FILE *fp, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx);
int UCI_PKEY_print_private_fp(FILE *fp, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx);
int UCI_PKEY_print_params_fp(FILE *fp, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx);
int UCI_PKEY_get_default_digest_nid(EVP_PKEY *pkey, int *pnid);
int UCI_PKEY_get_default_digest_name(EVP_PKEY *pkey, char *mdname, size_t mdname_sz);
int UCI_PKEY_digestsign_supports_digest(EVP_PKEY *pkey, OSSL_LIB_CTX *libctx, const char *name, const char *propq);
int UCI_PKEY_set1_encoded_public_key(EVP_PKEY *pkey, const unsigned char *pub, size_t publen);
size_t UCI_PKEY_get1_encoded_public_key(EVP_PKEY *pkey, unsigned char **ppub);
int UCI_CIPHER_param_to_asn1(EVP_CIPHER_CTX *c, ASN1_TYPE *type);
int UCI_CIPHER_asn1_to_param(EVP_CIPHER_CTX *c, ASN1_TYPE *type);
int UCI_CIPHER_set_asn1_iv(EVP_CIPHER_CTX *c, ASN1_TYPE *type);
int UCI_CIPHER_get_asn1_iv(EVP_CIPHER_CTX *c, ASN1_TYPE *type);
int UCI_PBE_scrypt(const char *pass, size_t passlen, const unsigned char *salt, size_t saltlen, uint64_t N, uint64_t r, uint64_t p, uint64_t maxmem, unsigned char *key, size_t keylen);
int UCI_PBE_scrypt_ex(const char *pass, size_t passlen, const unsigned char *salt, size_t saltlen, uint64_t N, uint64_t r, uint64_t p, uint64_t maxmem, unsigned char *key, size_t keylen, OSSL_LIB_CTX *ctx, const char *propq);
int UCI_PBE_CipherInit(ASN1_OBJECT *pbe_obj, const char *pass, int passlen, ASN1_TYPE *param, EVP_CIPHER_CTX *ctx, int en_de);
int UCI_PBE_CipherInit_ex(ASN1_OBJECT *pbe_obj, const char *pass, int passlen, ASN1_TYPE *param, EVP_CIPHER_CTX *ctx, int en_de, OSSL_LIB_CTX *libctx, const char *propq);
int UCI_PBE_alg_add_type(int pbe_type, int pbe_nid, int cipher_nid, int md_nid, EVP_PBE_KEYGEN *keygen);
int UCI_PBE_alg_add(int nid, const EVP_CIPHER *cipher, const EVP_MD *md, EVP_PBE_KEYGEN *keygen);
int UCI_PBE_find(int type, int pbe_nid, int *pcnid, int *pmnid, EVP_PBE_KEYGEN **pkeygen);
int UCI_PBE_find_ex(int type, int pbe_nid, int *pcnid, int *pmnid, EVP_PBE_KEYGEN **pkeygen, EVP_PBE_KEYGEN_EX **pkeygen_ex);
void UCI_PBE_cleanup(void);
int UCI_PBE_get(int *ptype, int *ppbe_nid, size_t num);
int UCI_PKEY_asn1_get_count(void);
const EVP_PKEY_ASN1_METHOD *UCI_PKEY_asn1_get0(int idx);
const EVP_PKEY_ASN1_METHOD *UCI_PKEY_asn1_find(ENGINE **pe, int type);
const EVP_PKEY_ASN1_METHOD *UCI_PKEY_asn1_find_str(ENGINE **pe, const char *str, int len);
int UCI_PKEY_asn1_add0(const EVP_PKEY_ASN1_METHOD *ameth);
int UCI_PKEY_asn1_add_alias(int to, int from);
int UCI_PKEY_asn1_get0_info(int *ppkey_id, int *pkey_base_id, int *ppkey_flags, const char **pinfo, const char **ppem_str, const EVP_PKEY_ASN1_METHOD *ameth);
const EVP_PKEY_ASN1_METHOD *UCI_PKEY_get0_asn1(const EVP_PKEY *pkey);
EVP_PKEY_ASN1_METHOD *UCI_PKEY_asn1_new(int id, int flags, const char *pem_str, const char *info);
void UCI_PKEY_asn1_copy(EVP_PKEY_ASN1_METHOD *dst, const EVP_PKEY_ASN1_METHOD *src);
void UCI_PKEY_asn1_free(EVP_PKEY_ASN1_METHOD *ameth);
void UCI_PKEY_asn1_set_public(EVP_PKEY_ASN1_METHOD *ameth, int (*pub_decode) (EVP_PKEY *pk,
                                                 const X509_PUBKEY *pub), int (*pub_encode) (X509_PUBKEY *pub,
                                                 const EVP_PKEY *pk), int (*pub_cmp) (const EVP_PKEY *a,
                                              const EVP_PKEY *b), int (*pub_print) (BIO *out,
                                                const EVP_PKEY *pkey,
                                                int indent, ASN1_PCTX *pctx), int (*pkey_size) (const EVP_PKEY *pk), int (*pkey_bits) (const EVP_PKEY *pk));
void UCI_PKEY_asn1_set_private(EVP_PKEY_ASN1_METHOD *ameth, int (*priv_decode) (EVP_PKEY *pk,
                                                   const PKCS8_PRIV_KEY_INFO
                                                   *p8inf), int (*priv_encode) (PKCS8_PRIV_KEY_INFO *p8,
                                                   const EVP_PKEY *pk), int (*priv_print) (BIO *out,
                                                  const EVP_PKEY *pkey,
                                                  int indent,
                                                  ASN1_PCTX *pctx));
void UCI_PKEY_asn1_set_param(EVP_PKEY_ASN1_METHOD *ameth, int (*param_decode) (EVP_PKEY *pkey,
                                                  const unsigned char **pder,
                                                  int derlen), int (*param_encode) (const EVP_PKEY *pkey,
                                                  unsigned char **pder), int (*param_missing) (const EVP_PKEY *pk), int (*param_copy) (EVP_PKEY *to,
                                                const EVP_PKEY *from), int (*param_cmp) (const EVP_PKEY *a,
                                               const EVP_PKEY *b), int (*param_print) (BIO *out,
                                                 const EVP_PKEY *pkey,
                                                 int indent,
                                                 ASN1_PCTX *pctx));
void UCI_PKEY_asn1_set_free(EVP_PKEY_ASN1_METHOD *ameth, void (*pkey_free) (EVP_PKEY *pkey));
void UCI_PKEY_asn1_set_ctrl(EVP_PKEY_ASN1_METHOD *ameth, int (*pkey_ctrl) (EVP_PKEY *pkey, int op,
                                              long arg1, void *arg2));
void UCI_PKEY_asn1_set_item(EVP_PKEY_ASN1_METHOD *ameth, int (*item_verify) (EVP_MD_CTX *ctx,
                                                const ASN1_ITEM *it,
                                                const void *data,
                                                const X509_ALGOR *a,
                                                const ASN1_BIT_STRING *sig,
                                                EVP_PKEY *pkey), int (*item_sign) (EVP_MD_CTX *ctx,
                                              const ASN1_ITEM *it,
                                              const void *data,
                                              X509_ALGOR *alg1,
                                              X509_ALGOR *alg2,
                                              ASN1_BIT_STRING *sig));
void UCI_PKEY_asn1_set_siginf(EVP_PKEY_ASN1_METHOD *ameth, int (*siginf_set) (X509_SIG_INFO *siginf,
                                                 const X509_ALGOR *alg,
                                                 const ASN1_STRING *sig));
void UCI_PKEY_asn1_set_check(EVP_PKEY_ASN1_METHOD *ameth, int (*pkey_check) (const EVP_PKEY *pk));
void UCI_PKEY_asn1_set_public_check(EVP_PKEY_ASN1_METHOD *ameth, int (*pkey_pub_check) (const EVP_PKEY *pk));
void UCI_PKEY_asn1_set_param_check(EVP_PKEY_ASN1_METHOD *ameth, int (*pkey_param_check) (const EVP_PKEY *pk));
void UCI_PKEY_asn1_set_set_priv_key(EVP_PKEY_ASN1_METHOD *ameth, int (*set_priv_key) (EVP_PKEY *pk,
                                                         const unsigned char
                                                            *priv,
                                                         size_t len));
void UCI_PKEY_asn1_set_set_pub_key(EVP_PKEY_ASN1_METHOD *ameth, int (*set_pub_key) (EVP_PKEY *pk,
                                                       const unsigned char *pub,
                                                       size_t len));
void UCI_PKEY_asn1_set_get_priv_key(EVP_PKEY_ASN1_METHOD *ameth, int (*get_priv_key) (const EVP_PKEY *pk,
                                                         unsigned char *priv,
                                                         size_t *len));
void UCI_PKEY_asn1_set_get_pub_key(EVP_PKEY_ASN1_METHOD *ameth, int (*get_pub_key) (const EVP_PKEY *pk,
                                                       unsigned char *pub,
                                                       size_t *len));
void UCI_PKEY_asn1_set_security_bits(EVP_PKEY_ASN1_METHOD *ameth, int (*pkey_security_bits) (const EVP_PKEY
                                                                *pk));
int UCI_PKEY_CTX_get_signature_md(EVP_PKEY_CTX *ctx, const EVP_MD **md);
int UCI_PKEY_CTX_set_signature_md(EVP_PKEY_CTX *ctx, const EVP_MD *md);
int UCI_PKEY_CTX_set1_id(EVP_PKEY_CTX *ctx, const void *id, int len);
int UCI_PKEY_CTX_get1_id(EVP_PKEY_CTX *ctx, void *id);
int UCI_PKEY_CTX_get1_id_len(EVP_PKEY_CTX *ctx, size_t *id_len);
int UCI_PKEY_CTX_set_kem_op(EVP_PKEY_CTX *ctx, const char *op);
const char *UCI_PKEY_get0_type_name(const EVP_PKEY *key);
int UCI_PKEY_CTX_set_mac_key(EVP_PKEY_CTX *ctx, const unsigned char *key, int keylen);
OSSL_DEPRECATEDIN_3_0 const EVP_PKEY_METHOD *UCI_PKEY_meth_find(int type);
OSSL_DEPRECATEDIN_3_0 EVP_PKEY_METHOD *UCI_PKEY_meth_new(int id, int flags);
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get0_info(int *ppkey_id, int *pflags, const EVP_PKEY_METHOD *meth);
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_copy(EVP_PKEY_METHOD *dst, const EVP_PKEY_METHOD *src);
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_free(EVP_PKEY_METHOD *pmeth);
OSSL_DEPRECATEDIN_3_0 int UCI_PKEY_meth_add0(const EVP_PKEY_METHOD *pmeth);
OSSL_DEPRECATEDIN_3_0 int UCI_PKEY_meth_remove(const EVP_PKEY_METHOD *pmeth);
OSSL_DEPRECATEDIN_3_0 size_t UCI_PKEY_meth_get_count(void);
OSSL_DEPRECATEDIN_3_0 const EVP_PKEY_METHOD *UCI_PKEY_meth_get0(size_t idx);
EVP_KEYMGMT *UCI_KEYMGMT_fetch(OSSL_LIB_CTX *ctx, const char *algorithm, const char *properties);
int UCI_KEYMGMT_up_ref(EVP_KEYMGMT *keymgmt);
void UCI_KEYMGMT_free(EVP_KEYMGMT *keymgmt);
const OSSL_PROVIDER *UCI_KEYMGMT_get0_provider(const EVP_KEYMGMT *keymgmt);
const char *UCI_KEYMGMT_get0_name(const EVP_KEYMGMT *keymgmt);
const char *UCI_KEYMGMT_get0_description(const EVP_KEYMGMT *keymgmt);
int UCI_KEYMGMT_is_a(const EVP_KEYMGMT *keymgmt, const char *name);
void UCI_KEYMGMT_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_KEYMGMT *keymgmt, void *arg), void *arg);
int UCI_KEYMGMT_names_do_all(const EVP_KEYMGMT *keymgmt, void (*fn)(const char *name, void *data), void *data);
const OSSL_PARAM *UCI_KEYMGMT_gettable_params(const EVP_KEYMGMT *keymgmt);
const OSSL_PARAM *UCI_KEYMGMT_settable_params(const EVP_KEYMGMT *keymgmt);
const OSSL_PARAM *UCI_KEYMGMT_gen_settable_params(const EVP_KEYMGMT *keymgmt);
EVP_PKEY_CTX *UCI_PKEY_CTX_new(EVP_PKEY *pkey, ENGINE *e);
EVP_PKEY_CTX *UCI_PKEY_CTX_new_id(int id, ENGINE *e);
EVP_PKEY_CTX *UCI_PKEY_CTX_new_from_name(OSSL_LIB_CTX *libctx, const char *name, const char *propquery);
EVP_PKEY_CTX *UCI_PKEY_CTX_new_from_pkey(OSSL_LIB_CTX *libctx, EVP_PKEY *pkey, const char *propquery);
EVP_PKEY_CTX *UCI_PKEY_CTX_dup(const EVP_PKEY_CTX *ctx);
void UCI_PKEY_CTX_free(EVP_PKEY_CTX *ctx);
int UCI_PKEY_CTX_is_a(EVP_PKEY_CTX *ctx, const char *keytype);
int UCI_PKEY_CTX_get_params(EVP_PKEY_CTX *ctx, OSSL_PARAM *params);
const OSSL_PARAM *UCI_PKEY_CTX_gettable_params(const EVP_PKEY_CTX *ctx);
int UCI_PKEY_CTX_set_params(EVP_PKEY_CTX *ctx, const OSSL_PARAM *params);
const OSSL_PARAM *UCI_PKEY_CTX_settable_params(const EVP_PKEY_CTX *ctx);
int UCI_PKEY_CTX_ctrl(EVP_PKEY_CTX *ctx, int keytype, int optype, int cmd, int p1, void *p2);
int UCI_PKEY_CTX_ctrl_str(EVP_PKEY_CTX *ctx, const char *type, const char *value);
int UCI_PKEY_CTX_ctrl_uint64(EVP_PKEY_CTX *ctx, int keytype, int optype, int cmd, uint64_t value);
int UCI_PKEY_CTX_str2ctrl(EVP_PKEY_CTX *ctx, int cmd, const char *str);
int UCI_PKEY_CTX_hex2ctrl(EVP_PKEY_CTX *ctx, int cmd, const char *hex);
int UCI_PKEY_CTX_md(EVP_PKEY_CTX *ctx, int optype, int cmd, const char *md);
int UCI_PKEY_CTX_get_operation(EVP_PKEY_CTX *ctx);
void UCI_PKEY_CTX_set0_keygen_info(EVP_PKEY_CTX *ctx, int *dat, int datlen);
EVP_PKEY *UCI_PKEY_new_mac_key(int type, ENGINE *e, const unsigned char *key, int keylen);
EVP_PKEY *UCI_PKEY_new_raw_private_key_ex(OSSL_LIB_CTX *libctx, const char *keytype, const char *propq, const unsigned char *priv, size_t len);
EVP_PKEY *UCI_PKEY_new_raw_private_key(int type, ENGINE *e, const unsigned char *priv, size_t len);
EVP_PKEY *UCI_PKEY_new_raw_public_key_ex(OSSL_LIB_CTX *libctx, const char *keytype, const char *propq, const unsigned char *pub, size_t len);
EVP_PKEY *UCI_PKEY_new_raw_public_key(int type, ENGINE *e, const unsigned char *pub, size_t len);
int UCI_PKEY_get_raw_private_key(const EVP_PKEY *pkey, unsigned char *priv, size_t *len);
int UCI_PKEY_get_raw_public_key(const EVP_PKEY *pkey, unsigned char *pub, size_t *len);
OSSL_DEPRECATEDIN_3_0
EVP_PKEY *UCI_PKEY_new_CMAC_key(ENGINE *e, const unsigned char *priv, size_t len, const EVP_CIPHER *cipher);
void UCI_PKEY_CTX_set_data(EVP_PKEY_CTX *ctx, void *data);
void *UCI_PKEY_CTX_get_data(const EVP_PKEY_CTX *ctx);
EVP_PKEY *UCI_PKEY_CTX_get0_pkey(EVP_PKEY_CTX *ctx);
EVP_PKEY *UCI_PKEY_CTX_get0_peerkey(EVP_PKEY_CTX *ctx);
void UCI_PKEY_CTX_set_app_data(EVP_PKEY_CTX *ctx, void *data);
void *UCI_PKEY_CTX_get_app_data(EVP_PKEY_CTX *ctx);
void UCI_SIGNATURE_free(EVP_SIGNATURE *signature);
int UCI_SIGNATURE_up_ref(EVP_SIGNATURE *signature);
OSSL_PROVIDER *UCI_SIGNATURE_get0_provider(const EVP_SIGNATURE *signature);
EVP_SIGNATURE *UCI_SIGNATURE_fetch(OSSL_LIB_CTX *ctx, const char *algorithm, const char *properties);
int UCI_SIGNATURE_is_a(const EVP_SIGNATURE *signature, const char *name);
const char *UCI_SIGNATURE_get0_name(const EVP_SIGNATURE *signature);
const char *UCI_SIGNATURE_get0_description(const EVP_SIGNATURE *signature);
void UCI_SIGNATURE_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_SIGNATURE *signature,
                                              void *data), void *data);
int UCI_SIGNATURE_names_do_all(const EVP_SIGNATURE *signature, void (*fn)(const char *name, void *data), void *data);
const OSSL_PARAM *UCI_SIGNATURE_gettable_ctx_params(const EVP_SIGNATURE *sig);
const OSSL_PARAM *UCI_SIGNATURE_settable_ctx_params(const EVP_SIGNATURE *sig);
void UCI_ASYM_CIPHER_free(EVP_ASYM_CIPHER *cipher);
int UCI_ASYM_CIPHER_up_ref(EVP_ASYM_CIPHER *cipher);
OSSL_PROVIDER *UCI_ASYM_CIPHER_get0_provider(const EVP_ASYM_CIPHER *cipher);
EVP_ASYM_CIPHER *UCI_ASYM_CIPHER_fetch(OSSL_LIB_CTX *ctx, const char *algorithm, const char *properties);
int UCI_ASYM_CIPHER_is_a(const EVP_ASYM_CIPHER *cipher, const char *name);
const char *UCI_ASYM_CIPHER_get0_name(const EVP_ASYM_CIPHER *cipher);
const char *UCI_ASYM_CIPHER_get0_description(const EVP_ASYM_CIPHER *cipher);
void UCI_ASYM_CIPHER_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_ASYM_CIPHER *cipher,
                                                void *arg), void *arg);
int UCI_ASYM_CIPHER_names_do_all(const EVP_ASYM_CIPHER *cipher, void (*fn)(const char *name, void *data), void *data);
const OSSL_PARAM *UCI_ASYM_CIPHER_gettable_ctx_params(const EVP_ASYM_CIPHER *ciph);
const OSSL_PARAM *UCI_ASYM_CIPHER_settable_ctx_params(const EVP_ASYM_CIPHER *ciph);
void UCI_KEM_free(EVP_KEM *wrap);
int UCI_KEM_up_ref(EVP_KEM *wrap);
OSSL_PROVIDER *UCI_KEM_get0_provider(const EVP_KEM *wrap);
EVP_KEM *UCI_KEM_fetch(OSSL_LIB_CTX *ctx, const char *algorithm, const char *properties);
int UCI_KEM_is_a(const EVP_KEM *wrap, const char *name);
const char *UCI_KEM_get0_name(const EVP_KEM *wrap);
const char *UCI_KEM_get0_description(const EVP_KEM *wrap);
void UCI_KEM_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_KEM *wrap, void *arg), void *arg);
int UCI_KEM_names_do_all(const EVP_KEM *wrap, void (*fn)(const char *name, void *data), void *data);
const OSSL_PARAM *UCI_KEM_gettable_ctx_params(const EVP_KEM *kem);
const OSSL_PARAM *UCI_KEM_settable_ctx_params(const EVP_KEM *kem);
int UCI_PKEY_sign_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_sign_init_ex(EVP_PKEY_CTX *ctx, const OSSL_PARAM params[]);
int UCI_PKEY_sign(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen);
int UCI_PKEY_verify_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_verify_init_ex(EVP_PKEY_CTX *ctx, const OSSL_PARAM params[]);
int UCI_PKEY_verify(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen);
int UCI_PKEY_verify_recover_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_verify_recover_init_ex(EVP_PKEY_CTX *ctx, const OSSL_PARAM params[]);
int UCI_PKEY_verify_recover(EVP_PKEY_CTX *ctx, unsigned char *rout, size_t *routlen, const unsigned char *sig, size_t siglen);
int UCI_PKEY_encrypt_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_encrypt_init_ex(EVP_PKEY_CTX *ctx, const OSSL_PARAM params[]);
int UCI_PKEY_encrypt(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen);
int UCI_PKEY_decrypt_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_decrypt_init_ex(EVP_PKEY_CTX *ctx, const OSSL_PARAM params[]);
int UCI_PKEY_decrypt(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen);
int UCI_PKEY_derive_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_derive_init_ex(EVP_PKEY_CTX *ctx, const OSSL_PARAM params[]);
int UCI_PKEY_derive_set_peer_ex(EVP_PKEY_CTX *ctx, EVP_PKEY *peer, int validate_peer);
int UCI_PKEY_derive_set_peer(EVP_PKEY_CTX *ctx, EVP_PKEY *peer);
int UCI_PKEY_derive(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen);
int UCI_PKEY_encapsulate_init(EVP_PKEY_CTX *ctx, const OSSL_PARAM params[]);
int UCI_PKEY_encapsulate(EVP_PKEY_CTX *ctx, unsigned char *wrappedkey, size_t *wrappedkeylen, unsigned char *genkey, size_t *genkeylen);
int UCI_PKEY_decapsulate_init(EVP_PKEY_CTX *ctx, const OSSL_PARAM params[]);
int UCI_PKEY_decapsulate(EVP_PKEY_CTX *ctx, unsigned char *unwrapped, size_t *unwrappedlen, const unsigned char *wrapped, size_t wrappedlen);
int UCI_PKEY_fromdata_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_fromdata(EVP_PKEY_CTX *ctx, EVP_PKEY **ppkey, int selection, OSSL_PARAM param[]);
const OSSL_PARAM *UCI_PKEY_fromdata_settable(EVP_PKEY_CTX *ctx, int selection);
int UCI_PKEY_todata(const EVP_PKEY *pkey, int selection, OSSL_PARAM **params);
int UCI_PKEY_export(const EVP_PKEY *pkey, int selection, OSSL_CALLBACK *export_cb, void *export_cbarg);
const OSSL_PARAM *UCI_PKEY_gettable_params(const EVP_PKEY *pkey);
int UCI_PKEY_get_params(const EVP_PKEY *pkey, OSSL_PARAM params[]);
int UCI_PKEY_get_int_param(const EVP_PKEY *pkey, const char *key_name, int *out);
int UCI_PKEY_get_size_t_param(const EVP_PKEY *pkey, const char *key_name, size_t *out);
int UCI_PKEY_get_bn_param(const EVP_PKEY *pkey, const char *key_name, BIGNUM **bn);
int UCI_PKEY_get_utf8_string_param(const EVP_PKEY *pkey, const char *key_name, char *str, size_t max_buf_sz, size_t *out_sz);
int UCI_PKEY_get_octet_string_param(const EVP_PKEY *pkey, const char *key_name, unsigned char *buf, size_t max_buf_sz, size_t *out_sz);
const OSSL_PARAM *UCI_PKEY_settable_params(const EVP_PKEY *pkey);
int UCI_PKEY_set_params(EVP_PKEY *pkey, OSSL_PARAM params[]);
int UCI_PKEY_set_int_param(EVP_PKEY *pkey, const char *key_name, int in);
int UCI_PKEY_set_size_t_param(EVP_PKEY *pkey, const char *key_name, size_t in);
int UCI_PKEY_set_bn_param(EVP_PKEY *pkey, const char *key_name, const BIGNUM *bn);
int UCI_PKEY_set_utf8_string_param(EVP_PKEY *pkey, const char *key_name, const char *str);
int UCI_PKEY_set_octet_string_param(EVP_PKEY *pkey, const char *key_name, const unsigned char *buf, size_t bsize);
int UCI_PKEY_get_ec_point_conv_form(const EVP_PKEY *pkey);
int UCI_PKEY_get_field_type(const EVP_PKEY *pkey);
int UCI_PKEY_paramgen_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_paramgen(EVP_PKEY_CTX *ctx, EVP_PKEY **ppkey);
int UCI_PKEY_keygen_init(EVP_PKEY_CTX *ctx);
int UCI_PKEY_keygen(EVP_PKEY_CTX *ctx, EVP_PKEY **ppkey);
int UCI_PKEY_generate(EVP_PKEY_CTX *ctx, EVP_PKEY **ppkey);
int UCI_PKEY_check(EVP_PKEY_CTX *ctx);
int UCI_PKEY_public_check(EVP_PKEY_CTX *ctx);
int UCI_PKEY_public_check_quick(EVP_PKEY_CTX *ctx);
int UCI_PKEY_param_check(EVP_PKEY_CTX *ctx);
int UCI_PKEY_param_check_quick(EVP_PKEY_CTX *ctx);
int UCI_PKEY_private_check(EVP_PKEY_CTX *ctx);
int UCI_PKEY_pairwise_check(EVP_PKEY_CTX *ctx);
int UCI_PKEY_set_ex_data(EVP_PKEY *key, int idx, void *arg);
void *UCI_PKEY_get_ex_data(const EVP_PKEY *key, int idx);
void UCI_PKEY_CTX_set_cb(EVP_PKEY_CTX *ctx, EVP_PKEY_gen_cb *cb);
EVP_PKEY_gen_cb *UCI_PKEY_CTX_get_cb(EVP_PKEY_CTX *ctx);
int UCI_PKEY_CTX_get_keygen_info(EVP_PKEY_CTX *ctx, int idx);
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_init(EVP_PKEY_METHOD *pmeth, int (*init) (EVP_PKEY_CTX *ctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_copy(EVP_PKEY_METHOD *pmeth, int (*copy) (EVP_PKEY_CTX *dst,
                                          const EVP_PKEY_CTX *src));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_cleanup(EVP_PKEY_METHOD *pmeth, void (*cleanup) (EVP_PKEY_CTX *ctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_paramgen(EVP_PKEY_METHOD *pmeth, int (*paramgen_init) (EVP_PKEY_CTX *ctx), int (*paramgen) (EVP_PKEY_CTX *ctx, EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_keygen(EVP_PKEY_METHOD *pmeth, int (*keygen_init) (EVP_PKEY_CTX *ctx), int (*keygen) (EVP_PKEY_CTX *ctx, EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_sign(EVP_PKEY_METHOD *pmeth, int (*sign_init) (EVP_PKEY_CTX *ctx), int (*sign) (EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen,
                  const unsigned char *tbs, size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_verify(EVP_PKEY_METHOD *pmeth, int (*verify_init) (EVP_PKEY_CTX *ctx), int (*verify) (EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen,
                    const unsigned char *tbs, size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_verify_recover(EVP_PKEY_METHOD *pmeth, int (*verify_recover_init) (EVP_PKEY_CTX *ctx), int (*verify_recover) (EVP_PKEY_CTX *ctx, unsigned char *sig,
                            size_t *siglen, const unsigned char *tbs,
                            size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_signctx(EVP_PKEY_METHOD *pmeth, int (*signctx_init) (EVP_PKEY_CTX *ctx,
                                                  EVP_MD_CTX *mctx), int (*signctx) (EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen,
                     EVP_MD_CTX *mctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_verifyctx(EVP_PKEY_METHOD *pmeth, int (*verifyctx_init) (EVP_PKEY_CTX *ctx,
                                                    EVP_MD_CTX *mctx), int (*verifyctx) (EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen,
                       EVP_MD_CTX *mctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_encrypt(EVP_PKEY_METHOD *pmeth, int (*encrypt_init) (EVP_PKEY_CTX *ctx), int (*encryptfn) (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen,
                       const unsigned char *in, size_t inlen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_decrypt(EVP_PKEY_METHOD *pmeth, int (*decrypt_init) (EVP_PKEY_CTX *ctx), int (*decrypt) (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen,
                     const unsigned char *in, size_t inlen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_derive(EVP_PKEY_METHOD *pmeth, int (*derive_init) (EVP_PKEY_CTX *ctx), int (*derive) (EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_ctrl(EVP_PKEY_METHOD *pmeth, int (*ctrl) (EVP_PKEY_CTX *ctx, int type, int p1,
                                          void *p2), int (*ctrl_str) (EVP_PKEY_CTX *ctx, const char *type, const char *value));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_digestsign(EVP_PKEY_METHOD *pmeth, int (*digestsign) (EVP_MD_CTX *ctx, unsigned char *sig, size_t *siglen,
                        const unsigned char *tbs, size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_digestverify(EVP_PKEY_METHOD *pmeth, int (*digestverify) (EVP_MD_CTX *ctx, const unsigned char *sig,
                          size_t siglen, const unsigned char *tbs,
                          size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_check(EVP_PKEY_METHOD *pmeth, int (*check) (EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_public_check(EVP_PKEY_METHOD *pmeth, int (*check) (EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_param_check(EVP_PKEY_METHOD *pmeth, int (*check) (EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_set_digest_custom(EVP_PKEY_METHOD *pmeth, int (*digest_custom) (EVP_PKEY_CTX *ctx,
                                                   EVP_MD_CTX *mctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_init(const EVP_PKEY_METHOD *pmeth, int (**pinit) (EVP_PKEY_CTX *ctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_copy(const EVP_PKEY_METHOD *pmeth, int (**pcopy) (EVP_PKEY_CTX *dst,
                                                  const EVP_PKEY_CTX *src));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_cleanup(const EVP_PKEY_METHOD *pmeth, void (**pcleanup) (EVP_PKEY_CTX *ctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_paramgen(const EVP_PKEY_METHOD *pmeth, int (**pparamgen_init) (EVP_PKEY_CTX *ctx), int (**pparamgen) (EVP_PKEY_CTX *ctx, EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_keygen(const EVP_PKEY_METHOD *pmeth, int (**pkeygen_init) (EVP_PKEY_CTX *ctx), int (**pkeygen) (EVP_PKEY_CTX *ctx, EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_sign(const EVP_PKEY_METHOD *pmeth, int (**psign_init) (EVP_PKEY_CTX *ctx), int (**psign) (EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen,
                    const unsigned char *tbs, size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_verify(const EVP_PKEY_METHOD *pmeth, int (**pverify_init) (EVP_PKEY_CTX *ctx), int (**pverify) (EVP_PKEY_CTX *ctx, const unsigned char *sig,
                      size_t siglen, const unsigned char *tbs, size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_verify_recover(const EVP_PKEY_METHOD *pmeth, int (**pverify_recover_init) (EVP_PKEY_CTX *ctx), int (**pverify_recover) (EVP_PKEY_CTX *ctx, unsigned char *sig,
                              size_t *siglen, const unsigned char *tbs,
                              size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_signctx(const EVP_PKEY_METHOD *pmeth, int (**psignctx_init) (EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int (**psignctx) (EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen,
                       EVP_MD_CTX *mctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_verifyctx(const EVP_PKEY_METHOD *pmeth, int (**pverifyctx_init) (EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int (**pverifyctx) (EVP_PKEY_CTX *ctx, const unsigned char *sig,
                          int siglen, EVP_MD_CTX *mctx));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_encrypt(const EVP_PKEY_METHOD *pmeth, int (**pencrypt_init) (EVP_PKEY_CTX *ctx), int (**pencryptfn) (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen,
                         const unsigned char *in, size_t inlen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_decrypt(const EVP_PKEY_METHOD *pmeth, int (**pdecrypt_init) (EVP_PKEY_CTX *ctx), int (**pdecrypt) (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen,
                       const unsigned char *in, size_t inlen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_derive(const EVP_PKEY_METHOD *pmeth, int (**pderive_init) (EVP_PKEY_CTX *ctx), int (**pderive) (EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_ctrl(const EVP_PKEY_METHOD *pmeth, int (**pctrl) (EVP_PKEY_CTX *ctx, int type, int p1, void *p2), int (**pctrl_str) (EVP_PKEY_CTX *ctx, const char *type,
                        const char *value));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_digestsign(const EVP_PKEY_METHOD *pmeth, int (**digestsign) (EVP_MD_CTX *ctx, unsigned char *sig, size_t *siglen,
                         const unsigned char *tbs, size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_digestverify(const EVP_PKEY_METHOD *pmeth, int (**digestverify) (EVP_MD_CTX *ctx, const unsigned char *sig,
                           size_t siglen, const unsigned char *tbs,
                           size_t tbslen));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_check(const EVP_PKEY_METHOD *pmeth, int (**pcheck) (EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_public_check(const EVP_PKEY_METHOD *pmeth, int (**pcheck) (EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_param_check(const EVP_PKEY_METHOD *pmeth, int (**pcheck) (EVP_PKEY *pkey));
OSSL_DEPRECATEDIN_3_0 void UCI_PKEY_meth_get_digest_custom(const EVP_PKEY_METHOD *pmeth, int (**pdigest_custom) (EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx));
void UCI_KEYEXCH_free(EVP_KEYEXCH *exchange);
int UCI_KEYEXCH_up_ref(EVP_KEYEXCH *exchange);
EVP_KEYEXCH *UCI_KEYEXCH_fetch(OSSL_LIB_CTX *ctx, const char *algorithm, const char *properties);
OSSL_PROVIDER *UCI_KEYEXCH_get0_provider(const EVP_KEYEXCH *exchange);
int UCI_KEYEXCH_is_a(const EVP_KEYEXCH *keyexch, const char *name);
const char *UCI_KEYEXCH_get0_name(const EVP_KEYEXCH *keyexch);
const char *UCI_KEYEXCH_get0_description(const EVP_KEYEXCH *keyexch);
void UCI_KEYEXCH_do_all_provided(OSSL_LIB_CTX *libctx, void (*fn)(EVP_KEYEXCH *keyexch, void *data), void *data);
int UCI_KEYEXCH_names_do_all(const EVP_KEYEXCH *keyexch, void (*fn)(const char *name, void *data), void *data);
const OSSL_PARAM *UCI_KEYEXCH_gettable_ctx_params(const EVP_KEYEXCH *keyexch);
const OSSL_PARAM *UCI_KEYEXCH_settable_ctx_params(const EVP_KEYEXCH *keyexch);
void UCI_add_alg_module(void);
int UCI_PKEY_CTX_set_group_name(EVP_PKEY_CTX *ctx, const char *name);
int UCI_PKEY_CTX_get_group_name(EVP_PKEY_CTX *ctx, char *name, size_t namelen);
int UCI_PKEY_get_group_name(const EVP_PKEY *pkey, char *name, size_t name_sz, size_t *gname_len);
OSSL_LIB_CTX *UCI_PKEY_CTX_get0_libctx(EVP_PKEY_CTX *ctx);
const char *UCI_PKEY_CTX_get0_propq(const EVP_PKEY_CTX *ctx);
const OSSL_PROVIDER *UCI_PKEY_CTX_get0_provider(const EVP_PKEY_CTX *ctx);

#ifdef __cplusplus
}
#endif

#endif /* UCI_EVP_AUTOGEN_H */
